# Generated by Django 4.2.13 on 2024-06-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0039_manifest_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='containerpullthroughremote',
            name='excludes',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='containerpullthroughremote',
            name='includes',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='containerremote',
            name='excludes',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='containerremote',
            name='includes',
            field=models.JSONField(null=True),
        ),
    ]
