# Generated by Django 4.2.16 on 2024-09-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0041_add_pull_through_pull_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifest',
            name='architecture',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='manifest',
            name='compressed_layers_size',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='manifest',
            name='os',
            field=models.TextField(null=True),
        ),
    ]
