# Generated by Django 4.2.16 on 2024-09-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0042_add_manifest_architecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifest',
            name='os',
            field=models.TextField(null=True),
        ),
    ]
