# Generated by Django 4.2.16 on 2024-09-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0043_add_manifest_os'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifest',
            name='compressed_layers_size',
            field=models.TextField(null=True),
        ),
    ]
